export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCES = 'PRODUCT_LIST_SUCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_LISTFULL_REQUEST = 'PRODUCT_LISTFULL_REQUEST';
export const PRODUCT_LISTFULL_SUCCESS = 'PRODUCT_LISTFULL_SUCCESS';
export const PRODUCT_LISTFULL_FAIL = 'PRODUCT_LISTFULL_FAIL'

export const PRODUCT_SEARCH_REQUEST = 'PRODUCT_SEARCH_REQUEST';
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT_SEARCH_SUCCESS';
export const PRODUCT_SEARCH_FAIL = 'PRODUCT_SEARCH_FAIL'
export const PRODUCT_SEARCH_RESET = 'PRODUCT_SEARCH_RESET'



export const CATEGORIES_LIST_REQUEST = 'CATEGORIES_LIST_REQUEST';
export const CATEGORIES_LIST_SUCCESS = 'CATEGORIES_LIST_SUCCESS';
export const CATEGORIES_LIST_FAIL = 'CATEGORIES_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_LIST_SUCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_LIST_FAIL';

export const  PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const  PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const  PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const  PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'


export const  PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const  PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const  PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'


export const  PRODUCT_EDIT_REQUEST = 'PRODUCT_EDIT_REQUEST'
export const  PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS'
export const  PRODUCT_EDIT_FAIL = 'PRODUCT_EDIT_FAIL'

export const  PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const  PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const  PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const  PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'


export const  PRODUCT_REVIEWADD_REQUEST = 'PRODUCT_REVIEWADD_REQUEST'
export const  PRODUCT_REVIEWADD_SUCCESS = 'PRODUCT_REVIEWADD_SUCCESS'
export const  PRODUCT_REVIEWADD_FAIL = 'PRODUCT_REVIEWADD_FAIL'
export const  PRODUCT_REVIEWADD_RESET = 'PRODUCT_REVIEWADD_RESET'

export const  CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const  CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const  CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

export const  REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST'
export const  REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS'
export const  REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL'

export const  REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST'
export const  REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS'
export const  REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL'
